MAX_CONNECTIONS = 20
POLL_INTERVAL_SECONDS = 0.5
EVENT_BATCH_SIZE = 100
MAX_STREAM_DURATION_SECONDS = 600.0
RETRY_DELAYS_SECONDS = (0.5, 1.0, 2.0)
STREAM_TOKEN_HEADER = "X-Stream-Token"
TERMINAL_JOB_STATUSES = frozenset({"COMPLETED", "FAILED"})

